/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
  implementation(project(":randomizers"))
  implementation(libs.jakarta.validation.jakarta.validation.api)
  implementation(project(":core"))
  testImplementation(libs.org.hibernate.validator.hibernate.validator)
  testImplementation(libs.org.glassfish.jakarta.el)
  testImplementation(libs.org.junit.jupiter.junit.jupiter)
  testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
  testImplementation(libs.org.assertj.assertj.core)
  testImplementation(libs.org.mockito.mockito.core)
  testImplementation(libs.org.mockito.mockito.junit.jupiter)
}

description = "k-random Bean Validation"
