plugins { kotlin("jvm") }

/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
  // keep-sorted start
  implementation(kotlin("stdlib"))
  implementation(libs.jakarta.validation.jakarta.validation.api)
  implementation(project(":core"))
  implementation(project(":randomizers"))
  testImplementation(libs.org.assertj.assertj.core)
  testImplementation(libs.org.glassfish.jakarta.el)
  testImplementation(libs.org.hibernate.validator.hibernate.validator)
  testImplementation(libs.org.junit.jupiter.junit.jupiter)
  testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
  testImplementation(libs.org.mockito.mockito.core)
  testImplementation(libs.org.mockito.mockito.junit.jupiter)
  // keep-sorted end
}

description = "k-random Bean Validation"

repositories { mavenCentral() }

kotlin { jvmToolchain(17) }
