plugins { alias(libs.plugins.kotlin.jvm) }

/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
  // keep-sorted start
  implementation(kotlin("reflect"))
  implementation(kotlin("stdlib"))
  implementation(libs.jakarta.validation.jakarta.validation.api)
  implementation(project(":core"))
  implementation(project(":randomizers"))
  testImplementation(libs.io.kotest.kotest.assertions.core)
  testImplementation(libs.io.mockk.mockk)
  testImplementation(libs.org.glassfish.jakarta.el)
  testImplementation(libs.org.hibernate.validator.hibernate.validator)
  testImplementation(libs.org.junit.jupiter.junit.jupiter)
  testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
  testImplementation(libs.org.junit.platform.engine)
  testImplementation(libs.org.junit.platform.launcher)
  // keep-sorted end
}

description = "k-random Bean Validation"

repositories { mavenCentral() }

kotlin { jvmToolchain(21) }
