/*
 * The MIT License
 *
 *   Copyright (c) 2023, Mahmoud Ben Hassine (mahmoud.benhassine@icloud.com)
 *
 *   Permission is hereby granted, free of charge, to any person obtaining a copy
 *   of this software and associated documentation files (the "Software"), to deal
 *   in the Software without restriction, including without limitation the rights
 *   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *   copies of the Software, and to permit persons to whom the Software is
 *   furnished to do so, subject to the following conditions:
 *
 *   The above copyright notice and this permission notice shall be included in
 *   all copies or substantial portions of the Software.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *   THE SOFTWARE.
 */
package io.github.krandom.randomizers.collection

import io.github.krandom.api.Randomizer
import io.github.krandom.randomizers.number.ByteRandomizer
import kotlin.math.abs

/**
 * A custom [Randomizer] that generates a list of random values using a delegate [ ].
 *
 * @param <T> the type of elements generated by this [Randomizer]
 * @author Eric Taix (eric.taix@gmail.com) </T>
 */
class ListRandomizer<T>
/**
 * Create a new [ListRandomizer] that will generate a list with a fixed number of elements. Each
 * element is generated by the [Randomizer] parameter
 *
 * @param elementRandomizer The [Randomizer] used to generate each element
 * @param nbElements The number of elements to generate
 */
@JvmOverloads
constructor(
  elementRandomizer: Randomizer<T>,
  nbElements: Int = abs(ByteRandomizer().getRandomValue().toInt()),
) : CollectionRandomizer<T>(elementRandomizer, nbElements) {

  override fun getRandomValue() = MutableList(nbElements) { randomElement }

  override fun toString() = "ListRandomizer [delegate=$delegate, nbElements=$nbElements]"
}
