/*
 * This file was generated by the Gradle 'init' task.
 */
// Note: version catalog (libs) is not available in settings scripts,
// so this version is also tracked in gradle/libs.versions.toml
plugins { id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0" }

rootProject.name = "k-random"

include(":randomizers")

include(":bean-validation")

include(":core")
