/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  `java-library`
  kotlin("jvm")
}

dependencies {
  api(libs.net.datafaker.datafaker)
  implementation(kotlin("stdlib"))
  implementation(project(":core"))
  testImplementation(libs.org.assertj.assertj.core)
  testImplementation(libs.org.junit.jupiter.junit.jupiter)
  testImplementation(libs.io.kotest.kotest.assertions.core)
}

description = "k-random Randomizers"

repositories { mavenCentral() }

kotlin { jvmToolchain(17) }
