/*
 * The MIT License
 *
 *   Copyright (c) 2023, Mahmoud Ben Hassine (mahmoud.benhassine@icloud.com)
 *
 *   Permission is hereby granted, free of charge, to any person obtaining a copy
 *   of this software and associated documentation files (the "Software"), to deal
 *   in the Software without restriction, including without limitation the rights
 *   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *   copies of the Software, and to permit persons to whom the Software is
 *   furnished to do so, subject to the following conditions:
 *
 *   The above copyright notice and this permission notice shall be included in
 *   all copies or substantial portions of the Software.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *   THE SOFTWARE.
 */
package io.github.krandom.randomizers.faker

import kotlin.random.Random

private const val BEGINNING_ANCHOR = """^\^"""
private const val END_ANCHOR = """\$\z"""

/**
 * A [io.github.krandom.annotation.Randomizer] that generates random strings matching a regular
 * expression.
 */
class RegularExpressionRandomizer
/**
 * Create a new [RegularExpressionRandomizer].
 *
 * @param regularExpression the regular expression which strings generated by this randomizer will
 *   match.
 * @param seed the initial seed
 */
@JvmOverloads
constructor(private val regularExpression: String, seed: Long = Random.nextLong()) :
  FakerBasedRandomizer<String>(seed) {

  override fun getRandomValue(): String {
    return faker.regexify(removeLeadingAndTailingBoundaryMatchers(regularExpression))
  }

  companion object {
    private fun removeLeadingAndTailingBoundaryMatchers(regularExpression: String): String =
      regularExpression
        .replaceFirst(BEGINNING_ANCHOR.toRegex(), "")
        .replaceFirst(END_ANCHOR.toRegex(), "")
  }
}
