/*
 * The MIT License
 *
 *   Copyright (c) 2023, Mahmoud Ben Hassine (mahmoud.benhassine@icloud.com)
 *
 *   Permission is hereby granted, free of charge, to any person obtaining a copy
 *   of this software and associated documentation files (the "Software"), to deal
 *   in the Software without restriction, including without limitation the rights
 *   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *   copies of the Software, and to permit persons to whom the Software is
 *   furnished to do so, subject to the following conditions:
 *
 *   The above copyright notice and this permission notice shall be included in
 *   all copies or substantial portions of the Software.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *   THE SOFTWARE.
 */
package io.github.krandom.randomizers.misc

import io.github.krandom.api.Randomizer
import io.github.krandom.randomizers.AbstractRandomizer

/**
 * A [Randomizer] which, according to the optional percent, returns the random value from a
 * delegate.
 *
 * @param <T> the type generated by this randomizer
 * @author Eric Taix (eric.taix@gmail.com) </T>
 */
class OptionalRandomizer<T>
/**
 * Create a new [OptionalRandomizer] with a delegate randomizer and an optional percent threshold.
 *
 * @param delegate The delegate to use to retrieve a random value
 * @param optionalPercent The percentage of randomized value to return (between 0 and 100)
 */
constructor(private val delegate: Randomizer<T>, optionalPercent: Int) : AbstractRandomizer<T?>() {
  private val optionalPercent: Int = optionalPercent.coerceIn(PERCENT_RANGE)

  override fun getRandomValue(): T? =
    if (random.nextInt(PERCENT_RANGE.last) <= optionalPercent) delegate.getRandomValue() else null

  companion object {
    private val PERCENT_RANGE = 0..100
  }
}
