name: Bump version and tag
on:
  workflow_run:
    workflows: ['CI-master']                     # runs after CI workflow
    types:
      - completed
jobs:
  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest
    # Only run one job a time to avoid conflicts
    concurrency: ci-${{ github.ref }}
    # This permission may be required to grant access for the Action to push tags
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: ./mvnw package

      - name: Increment version
        id: increment-version
        uses: RichardInnocent/semantic-versioning-maven@v0.1.0
