name: 'Kover Report'
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Generate kover coverage report
        run: ./gradlew koverXmlReport
      - name: Add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: |
            ${{ github.workspace }}/bean-validation/build/reports/kover/report.xml
            ${{ github.workspace }}/core/build/reports/kover/report.xml
            ${{ github.workspace }}/randomizers/build/reports/kover/report.xml
          title: Code Coverage
          update-comment: github.event_name == 'pull_request'
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          coverage-counter-type: LINE
