name: 'Reports'
on:
  workflow_run:
    workflows: ['CI-PR', 'CI-main']                     # runs after CI workflow
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Test report
        uses: dorny/test-reporter@v1
        with:
          artifact: reports                 # artifact name
          name: JUnit Tests                 # Name of the check run which will be created
          path: '**/TEST-*.xml'             # Path to test results (inside artifact .zip)
          reporter: java-junit              # Format of test results

      - name: Detekt report
        uses: natiginfo/action-detekt-all@1.23.7

      - name: Add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: |
            ${{ github.workspace }}/bean-validation/build/reports/kover/report.xml
            ${{ github.workspace }}/core/build/reports/kover/report.xml
            ${{ github.workspace }}/randomizers/build/reports/kover/report.xml
          title: Code Coverage
          update-comment: true
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          coverage-counter-type: LINE