name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI-PR', 'CI-main']                     # runs after CI workflow
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Test report
        uses: dorny/test-reporter@v2
        with:
          artifact: reports                 # artifact name
          name: JUnit Tests                 # Name of the check run which will be created
          path: '**/TEST-*.xml'             # Path to test results (inside artifact .zip)
          reporter: java-junit              # Format of test results
